import { Router } from 'express';
import { cancelSession, completeSession, createSession, listSessions, publicConfig, retrieveSession } from '../controllers/checkout';
import { createPayment, getPayment, cancelPayment, refundPayment, listTransactions, listMethods, createWebhook, getBalance, createPayout, listWebhookEventsController, listProviderConfigs } from '../controllers/payments';
import { deleteApiKey, getApiKeys, listAdmins, listApps, listLogs, listMerchants, postAdmin, postApiKey, postApp, postMerchant, rotateKey } from '../controllers/developer-platform';
import { createMarketplacePayout, createSplitPayment, createVendor, getMarketplaceAnalytics, getMarketplaceLedger, getVendorWallet, listEscrowHolds, listMarketplacePayouts, listMarketplaceTimeline, listMarketplaceWallets, listVendors, refundEscrow, releaseEscrow } from '../controllers/marketplace';

export const apiRouter = Router();
apiRouter.get('/config', publicConfig);
apiRouter.post('/checkout/sessions', createSession);
apiRouter.get('/checkout/sessions', listSessions);
apiRouter.get('/checkout/sessions/:id', retrieveSession);
apiRouter.post('/checkout/sessions/:id/complete', completeSession);
apiRouter.post('/checkout/sessions/:id/cancel', cancelSession);
apiRouter.post('/payments', createPayment);
apiRouter.get('/payments/:id', getPayment);
apiRouter.post('/payments/:id/cancel', cancelPayment);
apiRouter.post('/payments/:id/refund', refundPayment);
apiRouter.post('/webhooks', createWebhook);
apiRouter.get('/webhook-events', listWebhookEventsController);
apiRouter.get('/transactions', listTransactions);
apiRouter.get('/balance', getBalance);
apiRouter.post('/payouts', createPayout);
apiRouter.get('/payment-methods', listMethods);
apiRouter.get('/providers', listProviderConfigs);

apiRouter.post('/marketplace/split-payment', createSplitPayment);
apiRouter.post('/marketplace/vendors', createVendor);
apiRouter.get('/marketplace/vendors', listVendors);
apiRouter.get('/marketplace/vendors/:id/wallet', getVendorWallet);
apiRouter.post('/marketplace/payouts', createMarketplacePayout);
apiRouter.get('/marketplace/payouts', listMarketplacePayouts);
apiRouter.post('/marketplace/escrow/release', releaseEscrow);
apiRouter.post('/marketplace/escrow/refund', refundEscrow);
apiRouter.get('/marketplace/escrow', listEscrowHolds);
apiRouter.get('/marketplace/ledger', getMarketplaceLedger);
apiRouter.get('/marketplace/wallets', listMarketplaceWallets);
apiRouter.get('/marketplace/timeline', listMarketplaceTimeline);
apiRouter.get('/marketplace/analytics', getMarketplaceAnalytics);

apiRouter.get('/merchants', listMerchants);
apiRouter.post('/merchants', postMerchant);
apiRouter.get('/merchant-admins', listAdmins);
apiRouter.post('/merchant-admins', postAdmin);
apiRouter.get('/apps', listApps);
apiRouter.post('/apps', postApp);
apiRouter.get('/api-keys', getApiKeys);
apiRouter.post('/api-keys', postApiKey);
apiRouter.delete('/api-keys/:id', deleteApiKey);
apiRouter.post('/api-keys/:id/rotate', rotateKey);
apiRouter.get('/logs', listLogs);
